<a href="https://colab.research.google.com/github/sanjanabandi18/cse-c/blob/main/Copy_of_Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])

In [ ]:
print(arr)

[1 2 3]


In [ ]:
arr=np.array((4,5,6))

In [ ]:
print(arr)

[4 5 6]


In [ ]:
arr=np.array({7,8,9})

In [ ]:
print(arr)

{8, 9, 7}


In [ ]:
arr0=np.array(22)

In [ ]:
print(arr0)

22


In [ ]:
arr1=np.array([1,2])

In [ ]:
print(arr1)

[1 2]


In [ ]:
arr2=np.array([[1,2],[3,4]])

In [ ]:
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr3=np.array([[[1,2,3],[3,4,5]],[[3,4,5],[7,8,9]]])

In [ ]:
print(arr3)

[[[1 2 3]
  [3 4 5]]

 [[3 4 5]
  [7 8 9]]]


In [ ]:
arr0=np.array(22)
arr1=np.array([1,2])
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[[1,2,3],[3,4,5]],[[3,4,5],[7,8,9]]])
print(arr0.ndim)

0


In [ ]:
print(arr1.ndim)

1


In [ ]:
print(arr2.ndim)

2


In [ ]:
print(arr3.ndim)

3


In [ ]:
arr4=np.array([1,2,3,4,5],ndmin=4)

In [ ]:
print(arr4)

[[[[1 2 3 4 5]]]]


In [ ]:
print(arr4.ndim)

4


In [ ]:
print(arr1[1])

2


In [ ]:
arr1=np.array([1,2,3,4,5])

In [ ]:
print(arr1)

[1 2 3 4 5]


In [ ]:
print(arr1[1])

2


In [ ]:
print(arr1[-1])

5


In [ ]:
print(arr1[1:4])

[2 3 4]


In [ ]:
print(arr1[-1:-5])

[]


In [ ]:
print(arr1[-1:-4])

[]


In [ ]:
print(arr1[-4:-1])

[2 3 4]


In [ ]:
print(arr1[1:])

[2 3 4 5]


In [ ]:
print(arr1[:4])

[1 2 3 4]


In [ ]:
print(arr1[-4:])

[2 3 4 5]


In [ ]:
print(arr1[:-1])

[1 2 3 4]


In [ ]:
print(arr1[0:5:2])

[1 3 5]


In [ ]:
print(arr1)

[1 2 3 4 5]


In [ ]:
print(arr1[::2])

[1 3 5]


In [ ]:
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
print(arr2[1,1])

4


In [ ]:
print(arr2[0,1])

2


In [ ]:
print(arr2[1,0:2])

[3 4]


In [ ]:
print(arr2[1,1:2])

[4]


In [ ]:
print(arr3)

[[[1 2 3]
  [3 4 5]]

 [[3 4 5]
  [7 8 9]]]


In [ ]:
print(arr3[0,1,2])

5


In [ ]:
print(arr3[1,1,1])

8


In [ ]:
print(arr3[0,0,1])

2


In [ ]:
arr5=np.arange(1,10,2)

In [ ]:
print(arr5)

[1 3 5 7 9]


In [ ]:
arr6=np.arange(3)

In [ ]:
print(arr6)

[0 1 2]


In [ ]:
x=np.linspace(2,8,10)

In [ ]:
print(x)

[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.         6.66666667 7.33333333 8.        ]


In [ ]:
y=np.zeros((5,),dtype=int)

In [ ]:
print(y)

[0 0 0 0 0]


In [17]:
import numpy as np
z=np.ones((5,5))

In [18]:
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
print(np.empty([1,1]))

[[1.]]
